stages:
- name: build
  steps:
  - runScriptConfig:
      image: node:latest
      shellScript: |-
        npm install --global yarn
        ./scripts/update-dependencies
timeout: 60
notification: {}
