stages:
- name: build
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: rancher-ui/rancher-ui:v1
      registry: 127.0.0.1:34737
timeout: 60
notification: {}
