stages:
- name: build
  steps:
  - runScriptConfig:
      image: gcc:latest
      shellScript: |-
        curl -sL https://deb.nodesource.com/setup_12.x | bash -
        apt-get update
        apt-get install -y nodejs git
        npm install --global yarn
        yarn install && yarn cache clean
        ./scripts/update-dependencies
        ./scripts/build-static -s -l -c 'your-server.com'
- name: docker build
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: rancher-ui/rancher-ui:v1
      registry: 127.0.0.1:34737
timeout: 60
notification: {}
