stages:
- name: build
  steps:
  - runScriptConfig:
      image: gcc:latest
      shellScript: |-
        curl -sL https://deb.nodesource.com/setup_12.x | bash -
        apt-get update
        apt-get install -y nodejs git
        npm install --global yarn
        yarn install && yarn cache clean
        ./scripts/update-dependencies
        ./scripts/build-static -s -l -v'rancher-ui' -c 'a7a3f795df7a14107a4f9d67b13ab07b-989811488.ap-northeast-2.elb.amazonaws.com:8000'
- name: docker build
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: rancher-ui:${CICD_EXECUTION_SEQUENCE}
      registry: 127.0.0.1:34737
- name: deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 60
notification: {}
