stages:
- name: build
  steps:
  - runScriptConfig:
      image: node:latest
      shellScript: |-
        curl -sL https://deb.nodesource.com/setup_12.x | bash -
        npm install --global yarn
timeout: 60
notification: {}
